onlineVotingSystem/urls.py
from django.contrib import admin
from django.urls import path
from poll import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.homeView, name='home'),
    path('register/', views.registrationView, name='registration'),
    path('login/', views.loginView, name='login'),
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('logout/', views.logoutView, name='logout'),
    path('position/', views.positionView, name='position'),
    path('candidate/<int:pos>/', views.candidateView, name='candidate'),
    path('candidate/detail/<int:id>/', views.candidateDetailView, name='detail'),
    path('result/', views.resultView, name='result'),
    path('changepass/', views.changePasswordView, name='changepass'),
    path('editprofile/', views.editProfileView, name='editprofile'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/models.py
from django.contrib.auth.models import User
from django.db import models


class Position(models.Model):


    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

class Candidate(models.Model):

    name = models.CharField(max_length=100)
    total_vote = models.IntegerField(default=0, editable=False)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name="Candidate Pic", upload_to='images/')

    def __str__(self):
        return "{} - {}".format(self.name, self.position.title)

class ControlVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {} - {}".format(self.user, self.position, self.status)

poll/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.checks import messages
from django.core.exceptions import ValidationError
from datetime import date

from django.shortcuts import redirect, render


class RegistrationForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)

    date_of_birth = forms.DateField(
        label="Date of Birth",
        widget=forms.SelectDateWidget(years=range(1950, 2010))
    )

    phone_number = forms.CharField(
        max_length=10,
        label="Phone Number",
    )

    otp = forms.CharField(
        max_length=6,
        label="OTP (One-Time Password)",
        help_text="Enter the 6-digit OTP sent to your phone number."
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'date_of_birth', 'phone_number', 'otp']
        widgets = {
            'password': forms.PasswordInput,
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("The passwords do not match.")
        return cleaned_data


    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        today = date.today()
        age = today.year - date_of_birth.year - ((today.month, today.day) < (date_of_birth.month, date_of_birth.day))

        if age < 18:
            raise ValidationError("You must be at least 18 years old to register.")

        return date_of_birth

    from django.core.exceptions import ValidationError

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')

        try:
            # Attempt to convert the phone number to an integer
            phone_number_int = int(phone_number)
        except ValueError:
            # If conversion fails, raise a ValidationError with a popup-friendly message
            raise ValidationError("Please enter a valid phone number.")

        # Check if the phone number is within the desired range
        if not (6000000000 <= phone_number_int <= 9999999999):
            raise ValidationError("Phone number must be between 6,000,000,000 and 9,999,999,999")

        return phone_number


class ChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

poll/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import Candidate, ControlVote, Position
from .forms import ChangeForm
from onlineVotingSystem import settings





def homeView(request):
    return render(request, "poll/home.html")

from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from .forms import RegistrationForm  # Relative import corrected
from django.template.loader import render_to_string
from django.utils.html import strip_tags


def registrationView(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['password'] == cd['confirm_password']:
                obj = form.save(commit=False)
                obj.set_password(obj.password)
                obj.save()

                # Send registration email
                subject = 'Registration Confirmation'
                message = render_to_string('poll/registration_email.html', {'user': obj})
                plain_message = strip_tags(message)
                to_email = obj.email  # Assuming you have an email field in your registration model
                send_mail(subject, plain_message, settings.DEFAULT_FROM_EMAIL, [to_email], html_message=message)

                messages.success(request, 'You have been registered.')
                return redirect('home')
            else:
                return render(request, "poll/registration.html", {'form': form, 'note': 'Password must match'})
    else:
        form = RegistrationForm()

    return render(request, "poll/registration.html", {'form': form})





def loginView(request):
    if request.method == "POST":
        usern = request.POST.get('username')
        passw = request.POST.get('password')
        user = authenticate(request, username=usern, password=passw)
        if user is not None:
            login(request,user)
            return redirect('dashboard')
        else:
            messages.success(request, 'Invalid username or password!')
            return render(request, "poll/login.html")
    else:
        return render(request, "poll/login.html")

@login_required
def logoutView(request):
    logout(request)
    return redirect('home')
@login_required
def dashboardView(request):
    return render(request, "poll/dashboard.html")

@login_required
def positionView(request):

    obj = Position.objects.all()
    return render(request, "poll/position.html", {'obj':obj})
@login_required
def candidateView(request, pos):
    obj = get_object_or_404(Position, pk = pos)
    if request.method == "POST":
        temp = ControlVote.objects.get_or_create(user=request.user, position=obj)[0]
        if temp.status == False:
            temp2 = Candidate.objects.get(pk=request.POST.get(obj.title))
            temp2.total_vote += 1
            temp2.save()
            temp.status = True
            temp.save()
            return HttpResponseRedirect('/position/')
        else:
            messages.success(request, 'you have already been voted this position.')
            return render(request, 'poll/candidate.html', {'obj':obj})
    else:
        return render(request, 'poll/candidate.html', {'obj':obj})
@login_required
def resultView(request):
    obj = Candidate.objects.all().order_by('position','-total_vote')
    return render(request, "poll/result.html", {'obj':obj})

@login_required
def candidateDetailView(request, id):

    obj = get_object_or_404(Candidate, pk=id)
    return render(request, "poll/candidate_detail.html", {'obj':obj})
@login_required
def changePasswordView(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('dashboard')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, "poll/password.html", {'form':form})
@login_required
def editProfileView(request):

    if request.method == "POST":
        form = ChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = ChangeForm(instance=request.user)
    return render(request, "poll/edit_profile.html", {'form':form})

poll/templates/poll/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    {% csrf_token %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/114f8f7e3d.js"
      crossorigin="anonymous"
    ></script>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Online Voting System</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            <a class="nav-link" href="{% url 'editprofile' %}">Edit Profile</a>
            <a class="nav-link" href="{% url 'changepass' %}"
              >Change Password</a
            >
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-link" href="{% url 'registration' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class>{% block content %} {% endblock %}</div>
  </body>
</html>

poll/templates/poll/candidate.html
{% extends "poll/base.html" %} 
{% block title %}Candidate{% endblock %} 
{% block content %} 
{% if messages %} 
  {% for message in messages %}
    <div class="alert alert-danger" role="alert">{{ message }}</div>
  {% endfor %} 
{% endif %}

<br />
<div class="container-fluid as-full">
  <h3 class="card-title d-flex justify-content-center">
    Available Candidates for the Election of
  </h3>
  <h2 class="card-title d-flex justify-content-center">{{ obj.title }}</h2>
</div>
{% csrf_token %}
<br />
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %}
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th scope="col">Candidate</th>
                  <th scope="col">Vote</th>
                </tr>
              </thead>
              <tbody>
                {% for candidateID in obj.candidate_set.all %}
                <tr>
                  <td>
                    <a href="{% url 'detail' candidateID.id %}">{{candidateID.name}}</a>
                  </td>
                  <td>
                    <input
                      type="radio"
                      id="id_{{candidateID.id}}"
                      name="{{candidateID.position}}"
                      value="{{candidateID.id}}"
                      class="custom-control-input"
                      required
                    />
                  </td>
                </tr>
                {% empty %}
                  <p>No Candidates Available</p>
                {% endfor %}
              </tbody>
            </table>
            <input
              type="submit"
              class="col-md-12 btn btn-primary"
              value="Vote"
            />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<br />
<br />
<br />
<br />
<br />

<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          <a href="{% url 'position' %}" class="col-md-12 btn btn-primary">Go Back</a>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/candidate_detail.html
{% extends "poll/base.html" %}
{% block title %}Candidate Details{% endblock %}
{% block content %}
{% csrf_token %}
<br>
<div class="container-fluid as-full">
  <div class="row as-flex d-flex justify-content-center">
    <div class="col-5 align-self-center" >
      <div class="card border-primary mb-3 bg-dark" style="width: 25rem;">
        <div class="card-body">
          <div class="card border-primary mb-3 bg-light" style="width: 23rem;">
            <img src="{{ obj.image.url }}" class="card-img-top" alt="Candidate Image">
            <div class="card-body">
              <table class="table table-striped table-hover">
                <tbody>
                  <tr>
                    <td><b>Name</b></td>
                    <td>{{ obj.name }}</td>
                  </tr>
                  <tr>
                    <td><b>Competing For</b></td>
                    <td>{{ obj.position }}</td>
                  </tr>
                </tbody>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

<style>
  body{
    background: linear-gradient(45deg,#b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/dashboard.html
{% extends "poll/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
{% csrf_token %}
<br>
<h1 class="text-center">Welcome to Online Voting System</h1>
<h2 class="text-center">Hi, {{request.user.get_full_name }}</h2>
<section class="hero-section">
  <div class="card-grid">
    <a class="card  d-flex" href="{% url 'position' %}">
      <div class="card__background" style="background-image: url(https://img.freepik.com/free-vector/realistic-vector-icon-ballot-box-made-glass-hand-putting-voting-paper-inside-election-conce_134830-1493.jpg?w=2000)"></div>
      <div class="card__content">
        <p class="card__category">Vote</p>
        <h3 class="card__heading">Click Here To Vote</h3>
      </div>
    </a>
    <a class="card" href="{% url 'result' %}">
      <div class="card__background" style="background-image: url(https://media.istockphoto.com/id/1281075008/vector/success.jpg?s=612x612&w=0&k=20&c=79U0bXwmDlMwkBQ_qyzGItiRtItpXIQJsSKc2UlvQkk=)"></div>
      <div class="card__content">
        <p class="card__category">Result</p>
        <h3 class="card__heading">Click Here To See Result</h3>
      </div>
    </a>
  <div>
 </section>

<style>
  :root{
    --background-dark: #2d3548;
    --text-light: rgba(231, 231, 231, 0.9);
    --text-lighter: rgba(255, 255, 255, 0.9);
    --spacing-s: 8px;
    --spacing-m: 16px;
    --spacing-l: 24px;
    --spacing-xl: 32px;
    --spacing-xxl: 64px;
    --width-container: 1200px;
  }
  
  *{
    border: 0;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  
  html{
    height: 100%;
    font-family: 'Montserrat', sans-serif;
    font-size: 14px;
  }
  
  body{
    height: 100%;
    background: linear-gradient(45deg,#b57bee, #00e3fd);
  }
  
  .hero-section{
    align-items: flex-start;
    display: flex;
    min-height: 100%;
    justify-content: center;
    padding: var(--spacing-xxl) var(--spacing-l);
  }
  
  .card-grid{
    display: grid;
    grid-template-columns: repeat(1, 1fr);
    grid-column-gap: var(--spacing-l);
    grid-row-gap: var(--spacing-l);
    max-width: var(--width-container);
    width: 50%;
  }
  
  @media(min-width: 540px){
    .card-grid{
      grid-template-columns: repeat(2, 1fr); 
    }
  }
  
  @media(min-width: 960px){
    .card-grid{
      grid-template-columns: repeat(2, 1fr); 
    }
  }
  
  .card{
    list-style: none;
    position: relative;
    border-radius: var(--spacing-l);
  }
  
  .card:before{
    content: '';
    display: block;
    padding-bottom: 150%;
    width: 100%;
  }
  
  .card__background{
    background-size: cover;
    background-position: center;
    border-radius: var(--spacing-l);
    bottom: 0;
    filter: brightness(0.60) saturate(1.2) contrast(0.85);
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    transform-origin: center;
    transform: scale(1) translateZ(0);
    transition: 
      filter 200ms linear,
      transform 200ms linear;
  }
  
  .card:hover .card__background{
    transform: scale(1.05) translateZ(0);
  }
  
  .card-grid:hover > .card:not(:hover) .card__background{
    filter: brightness(0.5) saturate(0) contrast(1.2) blur(20px);
  }
  
  .card__content{
    left: 0;
    padding: var(--spacing-l);
    position: absolute;
    top: 0;
  }
  
  .card__category{
    color: var(--text-light);
    font-size: 0.9rem;
    margin-bottom: var(--spacing-s);
    text-transform: uppercase;
  }
  
  .card__heading{
    color: var(--text-lighter);
    font-size: 1.9rem;
    text-shadow: 2px 2px 20px rgba(0,0,0,0.2);
    line-height: 1.4;
    word-spacing: 100vw;
  }
</style>

{% endblock %}

poll/templates/poll/edit_profile.html
{% extends "poll/base.html" %}
{% block title %}Update Profile{% endblock %}
{% block content %}
{% load widget_tweaks %}

<br>
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          {% if note %}
          <h3 class="text text-muted">{{note}}</h3>
          {% endif %}
          <h5 class="card-title d-flex justify-content-center"> Update Profile</h5>
          <form action="" method="POST">
            {% csrf_token %}
              {% for field in form %}
              <div class="form-group">
                {% if field.errors %}
                  {% for error in field.errors %}
                    <ul>
                      <li>{{error}}</li>
                    </ul>
                  {% endfor %}
                {% endif %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{field.help_text}}</small>
                <br>
                  {% endif %}
                <br>
              </div>
            {% endfor %}
            <button type="submit" class="col-md-12 btn btn-primary">Update</button>
        </div>
      </div>
    </div>  
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/home.html
{% extends "poll/base.html" %} 
{% block title %}Online Voting System{%endblock%} 
{% block content %}
<br>
<div class="jumbotron">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-success" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <h1 class="display-4 d-flex justify-content-center">
    Welcome to Online Voting System
  </h1>
  <hr class="my-4 bg-dark d-flex justify-content-center" style="height: 2px" />
  <div class="d-flex justify-content-center">
    <img
      src="https://tse2.mm.bing.net/th?id=OIP.ZhCkog-XBq7TWW1y1rp47QHaEK&pid=Api&P=0&h=180"
      alt="Ballot Box"
      width="1000"
      height="400"
    />
  </div>

  <hr class="my-5 bg-dark d-flex justify-content-center" style="height: 2px" />

  <p class="lead d-flex justify-content-center">
    This is a simple voting system where you can vote for your favourite
    candidate.
  </p>
  <p class="lead d-flex justify-content-center">
    Admin can add candidates and post the election.
  </p>
  <p class="lead d-flex justify-content-center">
    User can vote for the candidates.
  </p>
</div>

<style>
  body {
    background: linear-gradient(white,white,white);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/login.html
{% extends "poll/base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-danger d-flex justify-content-center" role="alert">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <h5 class="card-title d-flex justify-content-center">User Login</h5>
          <form action="." method="POST">
            {% csrf_token %}
              <div class="form-group">
                <label for="id_username">Username:</label>
                <input type="text" name="username" class="form-control" id="id_username" required><i
                  class="iconinput fa fa-user"></i>
              </div>
              <div class="form-group">
                <label for="id_password">Password:</label>
                <input type="password" name="password" class="form-control" id="id_password" required><i
                  class="iconinput fa fa-keyboard"></i>
              </div>
            <button type="submit" class="col-md-12 btn btn-primary">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }

  .as-full {
    width: 100%;
    height: 100%;
  }

  .form-control {
    padding-left: 30px;
    padding-right: 30px;
  }

  .iconinput {
    position: relative;
    z-index: 1;
    left: 10px;
    top: -31px;
    width: 0;
  }
</style>

{% endblock %}

poll/templates/poll/password.html
{% extends "poll/base.html" %}
{% block title %}Change Password{% endblock %}
{% block content %}
{% load widget_tweaks %}

<br>
<br>
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Password Change Form</h5>
          <form action="." method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                {% if field.errors %}
                  {% for error in field.errors %}
                    <ul>
                      <li>{{error}}</li>
                    </ul>
                  {% endfor %}
                {% endif %}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                <br>
                {% if field.help_text %}
                  <small class="form-text text-muted">{{field.help_text}}</small>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="col-md-12 btn btn-primary">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/position.html
{% extends "poll/base.html" %} 
{% block title %} Position {% endblock %}
{% block content %}
<br />
<div class="container-fluid as-full">
  <h1 class="card-title d-flex justify-content-center">
    Available Position For Vote
  </h1>
</div>
<br />
<br />
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Position</th>
                <th scope="col">Vote</th>
              </tr>
            </thead>
            <tbody>
              {% for candidateID in obj %}
              <tr>
                <td>{{candidateID.title}}</td>
                <td>
                  <a
                    href="{% url 'candidate' candidateID.id %}"
                    class="btn btn-primary btn-sm"
                    >Vote</a
                  >
                </td>
              </tr>
              {% empty %}
              <p>No Positions Available</p>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}

poll/templates/poll/registration.html
{% extends "poll/base.html" %}
{% block title %}Registration{% endblock %}
{% block content %}
{% load widget_tweaks %}
<br />
<br />
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          {% if note %}
          <h3 class="text text-muted">{{note}}</h3>
          {% endif %}
          <h5 class="card-title">User Registration</h5>
          <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                {% if field.errors %}
                  {% for error in field.errors %}
                    <ul>
                      <li>{{error}}</li>
                    </ul>
                  {% endfor %}
                {% endif %}
                  {{ field.label_tag }}
                  {% render_field field class="form-control" %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{field.help_text}}</small>
                {% endif %}
              </div>
              <br>
            {% endfor %}
            <!-- Insert the reCAPTCHA widget here -->
            <div class="form-group">

            </div>
            <br> <!-- Optional: Add some spacing between the reCAPTCHA and the submit button -->
            <button type="submit" class="col-md-12 btn btn-primary">Register</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }

  .as-full {
    width: 100%;
    height: 100%;
  }

  .form-control {
    padding-left: 30px;
    padding-right: 30px;
  }
</style>

{% endblock %}

poll/templates/poll/registration_email.html
<!-- poll/templates/poll/registration_email.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Confirmation</title>
</head>
<body>
    <h2>Registration Confirmation</h2>
    <p>Dear {{ user.username }},</p>
    <p>Thank you for registering!</p>
    <!-- Add any other content you want to include in the email -->
</body>
</html>

poll/templates/poll/result.html
{% extends "poll/base.html" %} 
{% block title %}Result Page{% endblock %} 
{%block content %}
<h2 class="text-center">Result</h2>
<div class="container-fluid as-full">
  <div class="row as-full d-flex justify-content-center">
    <div class="col-5 align-self-center">
      <div class="card">
        <div class="card-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th scope="col">Candidate Name</th>
                <th scope="col">Candidate Position</th>
                <th scope="col">Total Vote</th>
              </tr>
            </thead>
            <tbody>
              {% for i in obj %}
              <tr>
                <td>{{ i.name }}</td>
                <td>{{ i.position }}</td>
                <td>{{ i.total_vote }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  body {
    background: linear-gradient(45deg, #b57bee, #00e3fd);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
</style>

{% endblock %}